### ISSUE TITLE
Can't type account name or password on login screen

### ISSUE THREAD

**Issue by hanscats** [ChimeraOS/chimeraos#212]
**Install**: New install of gamer-os 23 with the iso gameros-2020.10.02-x86_64.iso
**Graphics card/driver:** Intel 520/i3-6100

**Problem**: On the login screen I can't type with keyboard in the account name field or the password field. All the other buttons work like power and settings. I can also switch to terminal by ctrl+alt+F3 / F7, but terminal is garbled.

Same problem as described on https://steamcommunity.com/groups/steamuniverse/discussions/1/1760230157499060571/ although the Valve representative says this was sovled in an update in 2018 (post #56)

**Comment by hanscats** [comment]
Problem solved. Added more RAM and suddenly I was able to type into the fields... strange.

**Comment by barnabysunil** [comment]
i have another problem like that but i tried adding more RAM it doesn't work

**Comment by daddydaycare** [comment]
Same.  Cant enter credentials.  16 gigs of ram 4 core on i7. Will attempt reinstall.

**Comment by Zeitwaechter** [comment]
It pains me to say, that I now face a similar issue:

I logged in, via terminal, after I tried to get into Steam, but was blocked from proceeding (again), due to that one Screen that wants you to connect to the internet first, but fails to do so (for me), to let you proceed.
Normally I needed to update Steam itself, thant that worked again, but this time around it did not, as there was no update via pacman.

I then tried my luck updating manually, as the auto frzr updating systemd service always fails for me on boot.
It was then that I got the information about the gameros-24 update.
After that one had seemingly finished downloading+extracting (as the status for the systemd service inclined) I therefore rebooted my system.
And now I'm unable to login via shell anymore..

I do sometimes spot that the login worked, but I'm then forwarded to the login again.
`gamer` / `gamer` still works, therefore.

I did not try to do it via SSH.. which I will try now..

I also do not want to reinstall the OS another time and I do not want the feeling to persist that this is necessary on every bigger update, as this has also already happened for me from 22 > 23 :(

Will leave a comment after trying via SSH, but at least wanted to voice out, that there actually seems to be some issue.. anywhere at least :(

Cheers

**Comment by alkazar** [comment]
@Zeitwaechter Sorry to hear you are encountering issues. If I understand correctly, the issue is that you can log in, but Steam does not connect on startup? Perhaps your network connection is unstable or Steam itself is having some issues? In any case, I think it is a different issue than what was originally reported here.

**Comment by Zeitwaechter** [comment]
Hey, first let me thank you for your very fast reply :)

I'm sorry for not voicing out my issue better yesterday.

So, to recap:
I can't really login via termial as I'm directly forwarded back to the terminal's login.
I could not finish booting into Steam.

So, as an update:
Sometime, after XX reloads, it finally could update Steam like it wanted to.
It surely might have been an issue with my pihole instance.

Logging in via Terminal is still not working thogh.
Also no luck with uploading my ED25519 key via Steam Buddy, so I can login via SSH.
`ssh -v` has shown me that the key is introduced but not accepted.
Not so sure what is happening here, as ED25519 was also in the list of acceptable keys.

I mean, I'm fine for now, with how things are, as long as Steam works again, but I think you get my feeling :S
I can at least report that I do not face the issues others seem to have, that they can't play games anymore or other stuff - that worked out fine, then.

Let me know if and how I can be of help to you :+1: 

Cheers :)
