### ISSUE TITLE
Emulators run slow until compositor is toggled

### ISSUE THREAD

**Issue by matthew-parlette** [ChimeraOS/chimeraos#219]
I'm trying to play some NES and SNES emulators, but everything is very choppy when I first open the emulator.

I've found that I can get it running fine if I toggle the compositor via steam buddy, but I wanted to know if I can have this enabled by default, or if there was a way to get to the retroarch settings from within the game to make some adjustments.

Thanks!

**Comment by alkazar** [comment]
That is really strange. Do you have old hardware perhaps? We can't disable the compositor by default because that would seriously degrade the couch experience. But you can override the default window manager to openbox in a config file.

You can do that by adding `COMPOSITORCMD=openbox` to the config file as explained here: https://github.com/gamer-os/steamos-compositor-plus/#configuration
