### ISSUE TITLE
can't upgrade 24 to 25

### ISSUE THREAD

**Issue by mwprado** [ChimeraOS/chimeraos#257]

**Comment by mwprado** [comment]
I have tried upgrade via bpm and frz- deploy but it is not working. The second  option was showing checksum error. Even trying enter beta is not working. How to proceed?

**Comment by Samsagax** [comment]
Hello @mwprado. The 'update OS' function inside BPM does nothing as it is specific to SteamOS. To update your installation you should be able to do:
`$ sudo frzr-deploy chimeraos/chimeraos:stable`

If you get a checksum error that means the download failed and some checksum failsafes are not present in your release. You should be able to retry by deleting the `.img` file under `/frzr_root/`. That issue is fixed on newer releases.

**Comment by mwprado** [comment]
Thanks, but I tried delete img file, for a mistake I erase all frzr_root. Installing again.

Enviado do Yahoo Mail no Android 
 
  Em seg, 2 2e ago 2e 2021 às 11:36, Joaquín Ignacio ***@***.***> escreveu:   


Hello @mwprado. The 'update OS' function inside BPM does nothing as it is specific to SteamOS. To update your installation you should be able to do:
$ sudo frzr-deploy chimeraos/chimeraos:stable

If you get a checksum error that means the download failed and some checksum failsafes are not present in your release. You should be able to retry by deleting the .img file under /frzr_root/. That issue is fixed on newer releases.
