### ISSUE TITLE
Steam password needs to be entered too often

### ISSUE THREAD

**Issue by axelsimon** [ChimeraOS/chimeraos#275]
I don't turn on my ChimeraOS install very often, but it seems every time i need to re-enter my Steam password.

This is pretty annoying on a gamepad, and completely negates the point of a computer working as a console that you can just turn on, play, and turn off. It also means the computer (and the game collection it hosts) are unusable for anyone else in the household.

Is there anything that can be done to simply not have to enter the password? Or at least make the delay between password verification very long?

**Comment by Samsagax** [comment]
Do you game in another computer by any chance? Steam often logs you out if you log out and start games in another machine IIRC.

**Comment by alkazar** [comment]
I don't have this problem even when using Steam across three different ChimeraOS installs.
Are you certain you checked off "remember password"?

My best guess is if you do not login after a certain period, Steam revokes your login and forces you to re-enter your password.
What happens if you login, then shutdown the computer and immediately turn it on again?

Unfortunately we can't modify Steam and I don't know of any options to modify how long the password is remembered.
You would have to file a report with Valve.
