### ISSUE TITLE
Auto-mount USB / external / network drives

### ISSUE THREAD

**Issue by Tiger862000** [ChimeraOS/chimeraos#46]
Nice project! Love it. Thank you!
How can one mount external storage like USB, disks or network drives?
Despite my Linux knowledge I was not able to locate a mount point nor was I able to manually mount anything. So please, how to do that?

**Comment by sharkwouter** [comment]
Automatically mounting USB drives hasn't been implemented yet. I've done some testing in the past with a udv rule, but it still needs work.

The reason you're unable to mount manually is probably that you can't create the folder for it or you don't have the file system driver required installed. Try creating a directory in /tmp and mounting your drive there, see if it works.

Network drives are currently a bit harder to mount, you'd have make the root filesystem writable, which also disables automatic updates. You can do so with ``sudo frzr-unlock``. After that you can use pacman to install the cifs utils. Check out wiki.archlinux.org for morei info.

**Comment by alkazar** [comment]
You would have to drop to the command line, run `lsblk` to get a list of storage devices and their device paths. Then run `mount <device path> <mount path>`.

Not sure how you would mount a network drive. Probably depends on how it is set up.

What are you actually trying to accomplish though?

**Comment by ENKI101** [comment]
This is one of my questions, too.
I need autofs to mount nfs network drives and sync my savegames via simlinks.

**Comment by wallzero** [comment]
I would also like to mount network drives on boot using [`cifs-utils`](https://www.archlinux.org/packages/extra/x86_64/cifs-utils/) or [`nfs-utils`](https://www.archlinux.org/packages/core/x86_64/nfs-utils/).

I am comfortable modifying `/etc/fstab` to mount network drives on startup but `cifs-utils` and `nfs-utils` should be included in GamerOS. These packages are relatively small with few dependencies.

Please include `cifs-utils` and `nfs-utils` in future GamerOS updates.

**Comment by sharkwouter** [comment]
Have you tried using Kodi to transfer files from your network drive? I know it's not the solution which you'd like, but I am wondering if it works. Adding cifs-utils and nfs-utils might not be a bad idea, though.

**Comment by wallzero** [comment]
I'm not looking to transfer files, but host them. I think myself and others have a large NAS and prefer to have games/roms stored there. For example, on startup I'd like to mount an entire network volume to `/home/gamer/.local/share/steam-buddy/` in order to keep the roms and saves on a separate server.

**Comment by franchise2099** [comment]
I too am looking to adding a gaming drive.  I moved to GamerOS from SteamOS as I became tired of running on old Nvidia Drivers.  I love this project I am just a little concerned about the locked environment used for the ButterFS updates.  Do you think there will be an installer GUI that will accommodate a multi-HDD setup?   (example disc 1 = SSD 120 GB [boot drive] disc 2 = HDD 4 TB mounted on /home)  I also have a 40 TB NAS that contains oodels of ROMZ.

**Comment by bornagainpenguin** [comment]
Installed GamerOS today in hopes of being able to get my game on and enjoy my media collection with Kodi, as I'd heard it was possible to install it on GamerOS. On the games side, very few complaints.  Everything so far seems to have worked well though I really resent the inability to dualboot which would have made my life much easier.  On the Kodi side of things....

Well not so simple.  I keep my media on a large (10TB) external USB drive.  This is not mounted by GamerOS, so Kodi can't see it.  I tried seeing if I could connect it to my router and host it across the network--also a no go because GamerOS doesn't have Samba, doesn't mount network drives.  Somehow I've been transported back in time to 1997 where I am unable to get something as simple as a floppy drive to mount automatically never mind a CD or my iomega zip drive....  Nothing mounts.

The inability to mount USB, External and Network drives makes having Kodi something of a sick joke, as I don't understand how anyone expects to actually get their media on it. What am I missing?  I feel like I'm right on the edge of being able to have everything and yet so far away from anything but games.  A console without a media center is a step back.

Am I just being greedy for wanting it all?  Console experience, gaming and media center?

**Comment by Renevith** [comment]
I was able to get this to work with a USB drive using the command line. I agree it would be nice to have this better supported out of the box, as otherwise Kodi does seems fairly useless.

My steps to make it work were:
1. Make a directory where the disk can be mounted: `mkdir /home/gamer/media`
2. Let Kodi access this folder outside its sandbox: `flatpak --user override tv.kodi.Kodi --filesystem=/home/gamer/media`
3. Find the UUID and filesystem of the USB drive: `sudo blkid`
4. Add this line to /etc/fstab, except replace the UUID and ext3 with whatever `sudo blkid` said for your drive:
`UUID="b62a9aa1-c051-4f3f-be8b-636455eb6e46" /home/gamer/media ext3 rw,noatime 0 0`
5. Reboot to have it auto-mount, or just mount it yourself for now: `sudo mount /home/gamer/media`

I used a subdirectory of /home/gamer because I figured the home directory wouldn't be wiped out on an upgrade (or reboot), but I don't know that for sure. I only just started using ChimeraOS and I haven't upgraded since doing this. But it does work for now: after a reboot, I can just go into Kodi from Steam and still see all my videos without needing to do anything special.

**Comment by jarod186** [comment]
I have a similar problem, except its my dvd drive which is not mounting. I suspect that it is the same problem as with a dvd drive. Thank you @Renevith for that workaround, will try it!
Have used an old computer for my son and was planning to put chimera os on it but had to back out when i noticed that kodi could not play any of his dvd movies. 
The idea and concept for this project is awesome and hoping for some great future development for this! :)

**Comment by sharkwouter** [comment]
Lets wait and see how SteamOS 3 implements support for micro SD cards before we continue on this.

**Comment by Samsagax** [comment]
This one should be tracked in #237. Gamepadui already supports it and we included the pieces for it to work on newer ChimeraOS releases
