### ISSUE TITLE
Set default display for gamepad-ui? 

### ISSUE THREAD

**Issue by bdodroid** [ChimeraOS/chimeraos#530]
Is there a way to define which monitor steam/gamepad-ui uses on start up?

I have a dual monitor setup that works great, my main gaming monitor is used for gamepadui while the secondary is disabled 
(which I honestly don't mind at all), and both are active and usable perfectly in desktop mode, 
but the problem is when I try to add a third monitor (greedy I know) it switches the monitor gamepadui is using to the second monitor while my first and third monitors are disabled. 

 I have tried setting my primary display in desktop display settings but that doesnt appear to matter to gamepadui.

**Comment by TeamLinux01** [comment]
I also have a dual monitor setup and while it is using the monitor I would like it to use, it would be nice to know how it makes its decision to use the monitor.
Is there a configuration file that can be set to tell it what monitor to display the gamescope session?

**Comment by Samsagax** [comment]
You can set the prefered monitor in gamescope by setting the `-O` option. Currently we are setting  `-O *,eDP-1` to catch all monitors as primary and fallback to eDP (useful in handhelds for example).

To acchieve what you want you may need to override the entire `GAMESCOPECMD` variable since we don' t have a way to tell the monitor connector by variable. (Could you please report that issue as a Feature Request in gamescope-session repository?)

i.e. in a conf file under  `~/.config/environment.d/` put something like:
```
GAMESCOPECMD="/usr/bin/gamescope -e --xwayland-count 2 -O <your-monitor-connector>"
```

**Comment by bdodroid** [comment]
@Samsagax worked like a charm, thank you so much!
