### ISSUE TITLE
[Feature Request] KDE Plasma version?

### ISSUE THREAD

**Issue by bmfrosty** [ChimeraOS/chimeraos#568]
Any chance of a spin or other option where KDE Plasma is the DE instead of Gnome?  Last June I moved from pop_os to my Steam Deck for my daily driver, and intend to build a new desktop soon, and would love to use Chimera, but would prefer to stick with Plasma for consistency sake.

**Comment by pastaq** [comment]
We spent about a month evaluating multiple desktop environments before we added one, looking at the pro's and cons of each to determine the best fit for ChimeraOS. ChimeraOS is intended t o be a console experience by design where  the need f or the desktop is ideally none. Our mindset on the desktop is that it is a utility facilitator rather than a full fledged desktop experience. We needed something lightweight as the GH file size limit is 2GB (which is difficult  to manage even for a compressed image that contains an entire OS) and met the needs of users in the event there was a feature gap in one of the provided tools. Additionally, spinning up multiple distro's isn't  really something our update system supports. 

If that is a dealbreaker for you there are a few options. All of our custom packages are available in the AUR and can therefore be installed on any arch system. Endeavouros can install KDE by default and be configured in a similar way. I use it on my desktop and laptop in that configuration. You can also spin up your own fork of ChimeraOS by following the [guide in the wiki.](https://github.com/ChimeraOS/chimeraos/wiki/Development#forking) Nobara is also an excellent choice based on RedHat.

**Comment by thanone2** [comment]
This is just an excuse for using a macos like interface. The only difference between KDE Plasma and Gnome is the graphical interface.

**Comment by bmfrosty** [comment]
> This is just an excuse for using a macos like interface. The only difference between KDE Plasma and Gnome is the graphical interface.

Honestly, I've been all over the place.  OS-X for work for the last dozen years.  Gave up windows for gnome when pop-os was the hotness (2018 maybe?), and then moved to a steam-deck as my desktop when the laptop I bought from System76 died.  Then I decided to build a desktop and found that I wanted to stick with KDE.  Honestly tried Chimera after some blogger kept saying that SteamOS 3 stole everything from it, found that that blogger was being super-sensationalist, and then found a distribution that I did like that supported KDE.  

I could really not care less whether kde or gnome is more or less windows or os-x like.  I care whether it works with the workflow that I've built over time.

Either way, the developers of Chimera have said that they're not supporting KDE and anything further is super off-topic.  If you want KDE with Chimera, you can do as the developers have said and fork it.  I honestly have no interest in being a distribution maintainer, so I haven't.

**Comment by thanone2** [comment]
same, don't want that burden.
