### ISSUE TITLE
Extremely low framerate in most games

### ISSUE THREAD

**Issue by Soupstraw** [ChimeraOS/chimeraos#625]
I recently installed ChimeraOS on my old desktop PC. After a fresh install, I tried to play Divinity: Original Sin 2 and it seemed to work fine. After a reboot I got stuck on the "Downloading configuration upgrades" screen and then I decided to downgrade to 39 as suggested [here](https://github.com/ChimeraOS/chimeraos/issues/619#issuecomment-1550899233). After that I didn't have issues with the configuration upgrades screen, but Divinity and Untitled Goose Game ran at an extremely low framerate (~5 sec per frame). I'm suspecting it might have something to do with my GPU driver (I'm using GTX 1070, driver version 525.89.02). The issue remained after I upgraded back to 42.

**Comment by Samsagax** [comment]
Nvidia GPUs are not supported by gamescope (the compositor we use) at the moment. The downgrade to v39 would not work in the future since the steam client may break it´s old BPM. We do include nvidia drivers but Nvidia themselves only support vulkan extensions on newer hardware (I think is series 30 or newer) so there is nothing we can do on that front.
