### ISSUE TITLE
Performance Overlay Keeps Hiding

### ISSUE THREAD

**Issue by carabalb** [ChimeraOS/chimeraos#705]
Running into an issue where the performance overlay only appears temporarily if I move the mouse, otherwise it doesn't appear regardless of the performance overlay level. 

OS Version: 43.1
OS Build: 788f4bb
CPU: 7800x3d
GPU: 7900 XTX

**Comment by Samsagax** [comment]
Does it come back if you try to move the slider again? If not, that means mangoapp is dying on your hardware. Since you have all new hardware seems to be some bugs on the software stack yet to be fixed.

If you want to test a newer version, you can try latest `unstable` image to see if the issue is fixed.
If not I can try an prepare a test for you to debug the problem further.

**Comment by carabalb** [comment]
Thanks @Samsagax. Unfortunately the unstable branch did not fix my issue.

**Comment by carabalb** [comment]
Turning on "Force Composite" in the Developer section worked for me
