### ISSUE TITLE
I have no UEFI PC, need legacy BIOS installer ChimeraOS 39

### ISSUE THREAD

**Issue by chelaxian** [ChimeraOS/chimeraos#709]
Hello team!

Love your project and was happy that it was the best SteamOS clone for legacy BIOS PC.
But time left and you force update it to versions that not support legacy bios.
So after startup updating my chimeraos stop working.

I find last version that support legacy BIOS. it is
https://github.com/ChimeraOS/install-media/releases/tag/2023-02-15_432f20f

So i tied to install from that image but it need internet connection and when i give it - it start downloading last version 43-1 that is for UEFI-only.

How can i install and use ChimeraOS on legacy BIOS PC?
I can block github for ChimeraOS on my firewall after installation but I can't install it without internet connection to github for checking last version.

Is here fully offline-installer of  ChimeraOS v39 (2023-02-15/2023-02-17) ?
Or is here any trick to force installation media not to check latest release from github but this specific?
https://github.com/ChimeraOS/chimeraos/releases/tag/39_4cba43f

Thanks for helping!
I realy love ChimeraOS on legacy BIOS PC and want to continue using it.

**Comment by chelaxian** [comment]
can you recompile installation media for ChimeraOS v39 with no updates and with online connetc to specific release page not the latest? i think it will be usefull not only for me but for all people with legacy BIOS.

**Comment by Samsagax** [comment]
Hello @chelaxian . Unfortunately if your hardware can't boot into UEFI mode is probably too old to use this OS.

We dropped support for legacy BIOS because is broken on most modern configurations and is likely to be dropped in the future. UEFI has been around for almost 12 years now and is a standard that every piece of modern hardware supports.

That said, all our installers always look for the latest image online and downloads them. Using an old installer won't change that. If you have the tech skills you may get away with modifying the installer yourself. But most likely the image version you point to is already too old and won't be good for using.

**Comment by octuaOSdev** [comment]
)= how am i supposed to install it then? my second PC´s mobo. is too old
it has one of those old ones without even multi layerd menus aka being having a main menu

**Comment by octuaOSdev** [comment]
and no holo iso isnt working

**Comment by Samsagax** [comment]
I'm sorry but we can't support BIOS boot. Even the base distro dropped it in favor of UEFI boot.

Most of this OS is based on relatively new technologies, Vulkan in particular. That alone narrows hardware options to stuff made about 5  to 7 years ago.

**Comment by alkazar** [comment]
If you boot into the installer and exit early to get to the command line, you can edit the `install.sh` file to install a different version.

Find the line that says `TARGET="stable"` and change it to `TARGET="39"`.
Then run the `install.sh` script.
That will restart the installer which will download and install version 39 and pin you to that version indefinitely.

I don't know how well it will work though. The Steam client will still update and compatibility with the OS components is unknown.
