### ISSUE TITLE
Aya Neo Next - Control Stuttering and "Custom"/"Aya" buttons not working

### ISSUE THREAD

**Issue by majwhite** [ChimeraOS/chimeraos#810]
**Affected Versions**
- 44, 44-1 and 45 (279a080)

**Hardware**
- Aya Neo Next

**Issue Description**
I had not updated ChimeraOS for a while, but after an update to 44-1 I have found that the controller interactions "stutter" and take some time to "catch up" once an input has been given.

In addition to that, the "Custom"/"Aya" buttons have stopped functioning totally.

I did wonder if this is similar to #758 and wasn't sure whether the kernel update that was going to fix that issue would have fixed this one, but it seems that it hasn't.

I have tested on 44, 44-1 and the latest unstable 45 and all are exhibiting the same issue - I have pinned myself to 43-1 for now.

Let me know if there are any specific logs, etc that would help in debugging!

**Comment by pastaq** [comment]
I'll need you to be on 44-1 to get the relevant logging information.

Some questions, you will need to switch to a TTY by typing `ctrl+alt+f3` into an attached external keyboard
- Did you change the chimera-session at any point or are you using the default gamepadui session? You can verify this by typing `chimera-session` into a terminal, your selected session will have an * next to it.
- Can I get a copy of `journalctl -u handycon` during a boot when the problem is occuring.
- Does the problem happen if you change sessions by running `chimera-session gamepadui-with-qam`  (you can return to the original session by running `chimera-session gamepadui`)
- Run the command `cat /proc/bus/input/devices > ~/Downloads/input_devices` , this will create a file called `input_devices` that you can send me, either upload it to thiss issue using a web browser or use the discord flatpak to send me the file on our discord.

**Comment by majwhite** [comment]
Hey @pastaq!

Switched back to 44-1 to grab the logs

> Did you change the chimera-session at any point or are you using the default gamepadui session? You can verify this by typing chimera-session into a terminal, your selected session will have an * next to it.

Nope, it was still set to `gamepadui` when I checked.

> Can I get a copy of journalctl -u handycon during a boot when the problem is occuring.

Attached - [journalctl-handycon.txt](https://github.com/ChimeraOS/chimeraos/files/13402034/journalctl-handycon.txt)

> Does the problem happen if you change sessions by running `chimera-session gamepadui-with-qam` (you can return to the original session by running `chimera-session gamepadui`)

It doesn't - the stuttering goes away.  However, the "Custom"/"Aya" buttons are still not functional.

> Run the command cat /proc/bus/input/devices > ~/Downloads/input_devices , this will create a file called input_devices that you can send me, either upload it to thiss issue using a web browser

I've attached that here as well - [input-devices.txt](https://github.com/ChimeraOS/chimeraos/files/13402036/input-devices.txt)

**Comment by pastaq** [comment]
Looks like I made a mistake here.
https://github.com/ShadowBlip/HandyGCCS/blob/2f94eb9ae720abf00a8764dd8b217cdd8d30daa9/src/handycon/handhelds/aya_gen2.py#L46

The variable `active` should be `active_keys`

Give me a bit to push a new build and I'll give you some instructions to update the service.

**Comment by pastaq** [comment]
Alright, I updated the AUR with the fix. To install it:
```
sudo frzr-unlock
sudo pikaur -Sy handygccs-git
sudo systemctl restart handygccs
```

**Comment by majwhite** [comment]
Yep, that did the trick (after dealing with signature check problems!) - thanks so much for the quick fix @pastaq.

Is there anything special I have to do once this lands in the next stable release, or am I all safe to just upgrade?

**Comment by pastaq** [comment]
The fix will get pulled in to the next build, you'll be gtg
