### ISSUE TITLE
Please add select option for KDE or Gnome

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [ChimeraOS/chimeraos#968]
i have been using KDE for years and i hate bloated gnome

**Comment by pastaq** [comment]
Due to the nature of how the image is built this isn't possible currently. 

TBS, we use gnome partially because it uses less space on the image, so switching to KDE would cause more "bloat".

We're considering if we should switch to KDE in the future though, but t he earliest version that *might* happen would be v47. For now I'm going to close this.
